name: Build book

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      # Clone book repository
      - uses: actions/checkout@v4
        with:
          path: other

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          git clone https://github.com/assumptionsofphysics/book book
          # Clone autogen repository (target for the file)
          git clone https://gcarcassi:${{ secrets.AUTOGEN_TOKEN }}@github.com/assumptionsofphysics/autogen autogen
          # Output the directory contents for debugging
          ls -l
          # Use latexonline to build latest version
          cd book
          curl -L https://raw.githubusercontent.com/aslushnikov/latex-online/master/util/latexonline > laton && chmod 755 laton
          ls -l
          ./laton book.tex
          ls -l
          # Add possible changes
          cd ../autogen
          mv ../book.pdf AssumptionsOfPhysicsDraft.pdf
          git add AssumptionsOfPhysicsDraft.pdf
          # Commit and push only if there were changes
          if ! git diff --cached --quiet; then
            git config user.name "gcarcassi[bot]"
            git config user.email "gabriele.carcassi@gmail.com"
            git commit -m "Updating book dev version"
            git status
            echo "Will commit."
          else
            echo "No changes to commit."
          fi
