# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          path: book

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: grep openproblem *

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          git clone https://gcarcassi:${{ secrets.AUTOGEN_TOKEN }}@github.com/assumptionsofphysics/autogen autogen
          git clone https://github.com/assumptionsofphysics/tools tools
          ls -l
          python tools/problem-scraper/extractOpenProblems.py autogen/openproblems.yaml book/pm_EnsembleSpaces.tex
          cat autogen/openproblems.yaml
          cd autogen
          git config user.name "gcarcassi[bot]"
          git config user.email "gabriele.carcassi@gmail.com"
          git add openproblems.yaml
          git commit -m "Updating open problems"
          git push
          # Note: the following account information will not work on GHES
          # git add generated.txt
          # git commit -m "generated"
          # git push
